Pull Request
SelectQuoteLabs/SCPlus-Manage-Users-Page pull request #2
Opened 2021-07-30 17:20 UTC by Abdul0046

2021-07-30 17:40 UTC, lucas-homer commented
For frontend PRs, we always include some sort of visual aid that shows the changes to the UI. Most of the time this takes the form of a Loom video, and in simpler cases a screenshot is fine. I just sent you an invite for Loom to your selectquote email so you can get set up with that. The video doesn't need to be anything too complicated. Simply demonstrate what the PR's code adds. Also -- we have a doc for "what makes a good PR" https://selectquote.atlassian.net/wiki/spaces/SE/pages/839745693/What+makes+a+Great+PR

2021-07-30 17:51 UTC, Abdul0046 commented
> For frontend PRs, we always include some sort of visual aid that shows the changes to the UI. Most of the time this takes the form of a Loom video, and in simpler cases a screenshot is fine. I just sent you an invite for Loom to your selectquote email so you can get set up with that. The video doesn't need to be anything too complicated. Simply demonstrate what the PR's code adds. Also -- we have a doc for "what makes a good PR" https://selectquote.atlassian.net/wiki/spaces/SE/pages/839745693/What+makes+a+Great+PR

Sure I'll make one

2021-08-03 16:54 UTC, lucas-homer requested changes
We should abandon SideNavIcons and review the MIAV repo for reference/guidance. Feel free to respond with any questions about that you may have

2021-08-03 16:54 UTC, lucas-homer commented on src/components/SideNavBar.js
> +        <SideNavIcons>
[blocker] I would've expected an IconButton component here. We should review the multi-instance-admin-view repo for guidance

2021-08-03 16:54 UTC, lucas-homer commented on src/components/SideNavBar.js
> +        <SideNavIcons>
similar comment here. We should review our example repo (multi-instance-admin-view) for guidance on how to build a sidenav and buttons in the sidenav

2021-08-03 17:17 UTC, Abdul0046 commented on src/components/SideNavBar.js
> +        <SideNavIcons>
Got it. I will use IconButtons for this.

2021-08-03 17:18 UTC, Abdul0046 commented on src/components/SideNavBar.js
> +        <SideNavIcons>
I will surely look into the code. Actually, I tried to build it by myself so I didn't refer to multi-instance admin view

2021-08-03 17:40 UTC, Abdul0046 commented on src/components/SideNavBar.js
> +        <SideNavIcons>
If you are referring to that SideNavIcons that's a component I made

2021-08-10 13:07 UTC, merged