manage-user-page-crud
SelectQuoteLabs/SCPlus-Manage-Users-Page pull request #6
Opened 2021-08-12 18:16 UTC by Abdul0046

https://www.loom.com/share/5bd8f4bcba6947c89574ff2756a81216

2021-08-12 18:41 UTC, lucas-homer requested changes

2021-08-12 18:41 UTC, lucas-homer commented on pages/manage-users/index.js
> +export default function ManageUsers() {
we would normally just make a file called `pages/manage-users.js`. Not a blocker, but wanted to note that.

2021-08-12 18:41 UTC, lucas-homer commented on src/components/Body.js
> -      <Snackbar
I think I may have said we don't need Snackbar, but I think we should go ahead and keep it. This way you can implement our typical error handling inside a react-query hook, where in the `onError` callback we would `snackbar.error('There was an error fetching users')`

2021-08-12 18:41 UTC, lucas-homer commented on src/components/ManageUserAccordion.js
> +  const dummyUsers = () => {
[blocker] we should get rid of this function, as it's unnecessary. Our pattern is to define a variable `columns` rather than inlining it in the JSX. See SeniorActionTable.tsx for a good example.

2021-08-12 18:41 UTC, lucas-homer commented on src/components/ManageUserGrid.js
> +    <Grid container className={classes.root}>
[blocker] we need to refer back to AdminViewGrid. The responsive values (line 30 for example) are not what we want. Our users will not use an admin view on any sort of small screen, so we only want a simple two-column grid, which you can see an example of in AdminViewGrid.

2021-08-16 23:00 UTC, lucas-homer requested changes

2021-08-16 23:00 UTC, lucas-homer commented on src/components/SideNavBar.js
> +        <ManageAddUser
[blocker] this should only be a button that links us to the manage users route. please refer back to the MIAV's SideNavBar for an example

2021-08-16 23:00 UTC, lucas-homer commented on src/components/ManageUserForm.js
> +    <Card style={{ padding: 16 }}>
[blocker] we need to use SQFormScrollableCard instead. Please see MIAV for examples (search "DetailsCard" and you'll find several that consume SQFormScrollableCard)

2021-08-16 23:00 UTC, lucas-homer commented on src/components/ManageAddUser.js
> +  const mutation = useMutation((data) => onSubmitCreateUserData(data), {
[blocker] normally we put our mutation hooks in their own file, so we would not have access to closing the modal inside the `onSuccess` callback. Additionally, though, we would use SQFormDialog for this Dialog.

2021-08-17 10:13 UTC, Abdul0046 commented on src/components/ManageAddUser.js
> +  const mutation = useMutation((data) => onSubmitCreateUserData(data), {
I already did that and I told you in the meeting as well that I have created the hooks for fetching and for mutation. But first I committed the earlier changes you told me. :)

2021-08-17 10:59 UTC, Abdul0046 commented on src/components/SideNavBar.js
> +        <ManageAddUser
I am using this to add the users

2021-08-17 11:00 UTC, Abdul0046 commented on src/components/SideNavBar.js
> +        <ManageAddUser
Should I change it?

2021-08-18 17:16 UTC, lucas-homer commented on pages/manage-users.js
> +    <div className={classes.root}>
let's take what's inside ManageUserGrid and put it directly in this file so we don't need a separate ManageUserGrid file.

2021-08-18 17:17 UTC, lucas-homer commented on src/components/ManageUserGrid.js
> +  const handleSelectedUserChange = (userData) => {
[nit] let's simplify the name of this function to -- handleSelectUser

2021-08-18 17:20 UTC, lucas-homer commented on src/components/ManageUserGrid.js
> +      <ManageFetchUserData
[nit] we can call this UserTable and on line 30, that can be called UserDetails

2021-08-18 17:22 UTC, lucas-homer commented on src/hooks/useAddUserData.js
> +export const useAddUserData = () => {
this can be called `useAddUser` or a name that matches our pattern in MIAV even more is `useCreateUser`

2021-08-18 17:23 UTC, lucas-homer commented on src/hooks/useFetchAllUsersData.js
> +export const useFetchAllUsersData = () => {
this can be called `useUsers`

2021-08-18 17:27 UTC, lucas-homer commented on src/components/ManageUserForm.js
> +  const handleUserPostSubmit = (data) => {
in this component, we should import our `useUpdateUser` mutation hook, and then we instantiate the mutation hook, so that inside this function, we can write `updateUser.mutateAsync(data)`. See SeniorActionDetailsCard.tsx for a good example.

2021-08-18 17:31 UTC, lucas-homer commented on src/components/ManageAddUser.js
> +const ManageAddUser = ({
let's call this AddUserDialog

2021-08-18 17:45 UTC, lucas-homer commented on src/components/SideNavBar.js
> +        <ManageAddUser
to review -- this line should be an IconButton component, and its `onClick` event should be the `openDialog` function returned by our `useCreateDialog` hook. To implement the `useCreateDialog` hook and its provider component, as well as `useCreateDialogState` and `useCreateDialogDispatch`, see CreateDialogContext.tsx for reference. To see an example of how we use those hooks, see SideNavBar.tsx and, for example, src/components/ManagePhoneSystemCampaigns/index.tsx

2021-08-23 15:51 UTC, lucas-homer requested changes

2021-08-23 15:51 UTC, lucas-homer commented on src/hooks/useUpdateUser.js
> +      queryClient.invalidateQueries('userData');
[blocker] this needs to happen inside `onSettled` because we need to revalidate whether it was successful or it failed due to an error.

2021-08-23 15:51 UTC, lucas-homer commented on src/components/SideNavIcons.js
>  import { IconButton, Avatar } from 'scplus-shared-components';
as I have already said, this entire file is unnecessary.

2021-08-23 15:51 UTC, lucas-homer commented on src/components/SideNavBar.js
> +        {isCreateDialogButtonDisabled ? (
[blocker] this is not what we discussed. all we need inside SideNavTop is an IconButton. Please review again the SideNavBar component in the muli-instance-admin-view (MIAV) code

2021-08-23 15:51 UTC, lucas-homer commented on src/components/SideNavBar.js
>    const [isOpen, setIsOpen] = React.useState(false);
[blocker] as we discussed last week, this useState should not exist. We should see the add-user dialog component inside the manage-users page component

2021-08-23 15:51 UTC, lucas-homer commented on src/components/ManageAddUser.js
> +    addUserData.mutateAsync(data);
[blocker] this is an async function, so we need to make `handlePostUserData` an async function as well and then we can correctly await the mutateAsync before closing the dialog, which should only happen when we _successfully_ create the new user record.

2021-08-23 16:00 UTC, Abdul0046 commented on src/components/SideNavBar.js
>    const [isOpen, setIsOpen] = React.useState(false);
I am still working on it. As I mentioned on the commit I created the update hook. Maybe I should have told you before or I should have mentioned on the commit. Sorry.

2021-08-23 16:01 UTC, Abdul0046 commented on src/components/SideNavBar.js
> +        {isCreateDialogButtonDisabled ? (
I am on it I have created the CreateDialogContext I am just reassembling the code.

2021-08-23 16:02 UTC, Abdul0046 commented on src/components/SideNavIcons.js
>  import { IconButton, Avatar } from 'scplus-shared-components';
I may have forgot about it I thought you only said to remove the ManageUserGrid

2021-08-23 16:03 UTC, Abdul0046 commented on src/hooks/useUpdateUser.js
> +      queryClient.invalidateQueries('userData');
Okay

2021-08-24 16:53 UTC, lucas-homer requested changes

2021-08-24 16:53 UTC, lucas-homer commented on src/components/ManageAddUser.js
> +    await addUserData.mutateAsync(data);
[blocker] if this errors, how do we avoid closing the dialog? search the MIAV project for `handleSubmit` and you'll find the answer

2021-08-24 16:53 UTC, lucas-homer commented on src/components/SideNavBar.js
> +        <IconButton
close! however, in this case, I think we can lose the `IconButton` and wrap the Avatar with Link and that'd be enough. Like this, which I copy/pasted from `SideNavLink` in MIAV:
```
<Link href={href}>
  <a style={{ textDecoration: 'none' }}>
    <Tooltip title={title} placement="right" arrow={true}>
      <div>
        <Avatar isInverted isFocused={href === pathname}>
          {avatarLetter.toUpperCase()}
        </Avatar>
      </div>
    </Tooltip>
  </a>
</Link>
```

2021-08-24 18:52 UTC, lucas-homer commented on src/components/ManageAddUser.js
> +    await addUserData.mutateAsync(data);
that isn't how we've done it in MIAV, where we wrap it in a try/catch, but I think I like this solution better! nice work

2021-08-24 18:53 UTC, lucas-homer approved these changes

2021-08-24 18:55 UTC, merged